name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:14-slim
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:16-bullseye
        with:
          entrypoint: '/bin/echo'
          args: 'Hello Beef'
      - name: Step with docker
        uses: docker://node:16-bullseye
        with:
          entrypoint: '/usr/local/bin/node'
          args: '-v'
